config/routes.rb
Stock::Application.routes.draw do
  resources :analyses

  get "chart/draw"

  resources :quotes

  resources :syms

  resources :setcloses

  match '/quotes/search(/:id)', :controller => :quotes, :action => :search
  match '/chart/draw/:id', :controller => :chart, :action => :draw
  match '/analyses/draw/:symbol/:date/:time', :controller => :analyses, :action => :draw
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/quote.rb
class Quote
  include Mongoid::Document
  field :date, :type => String
  field :time, :type => String
  field :symbol, :type => String
  field :close, :type => Float
  field :change, :type => Float
  field :perc_change, :type => Float
  field :volume, :type => Integer
  field :value, :type => Integer
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.page(params[:page])
    @setcloses = Setclose.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote = Quote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(params[:quote])

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render json: @quote, status: :created, location: @quote }
      else
        format.html { render action: "new" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])

    respond_to do |format|
      if @quote.update_attributes(params[:quote])
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :ok }
    end
  end

  def search
    @symbol = params[:id]
    @setcloses = Quote.where('date' => today, 'symbol' => 'SET').order(['date',1],['time',1]).page(params[:page])
    @quotes = Quote.where('date' => today,'symbol' => @symbol).order(['date',1],['time',1]).page(params[:page])
    render "index"
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :close %><br />
    <%= f.text_field :close %>
  </div>
  <div class="field">
    <%= f.label :change %><br />
    <%= f.text_field :change %>
  </div>
  <div class="field">
    <%= f.label :perc_change %><br />
    <%= f.text_field :perc_change %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.number_field :volume %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<h1><%= link_to "See full chart for #{@symbol}", "/chart/draw/#{@symbol}", :html_output => {'target' => '_blank'} %></h1>

<script type="text/javascript" charset="utf-8">
$(function(){
  new Highcharts.Chart({
    chart: {
      renderTo: "symbol_chart"
    }
    ,title: {
      text: "STOCK Chart"
    }
    ,xAxis: {
      categories: <%= raw @quotes.map { |d| d['time'] } %>
      ,labels: {
        align: 'center'
        ,step: 1
	,rotation: 315
	,y: 20
      }
    }
    ,yAxis: [{
      title: {
        text: "Price"
      }
    },{
        opposite: true
        ,labels: {
          formatter: function() {
            return this.value + ' Shares';
          }
          ,enabled: true
        }
        ,gridLineWidth: 0
        ,title: {
          text: 'Volume'
          ,style: { color: '#4500A7' }
        }
    },{
        opposite: false
        ,gridLineWidth: 0
        ,title: {
          text: 'SET'
          ,style: { color: '#450000' }
        }
    }]
    ,tooltip: {
      crosshairs: true
      ,shared: true
    }
    ,series: [{
      name: 'Close'
      ,data: <%= @quotes.map { |d| d.close } %>
      ,zIndex: 1
    },{
      name: 'Volume'
      ,data: <%= @quotes.map { |d| d.vol_diff } %>
      ,type: 'column'
      ,yAxis: 1
    },{
      name: 'SET'
      ,data: <%= @setcloses.map { |d| d.close } %>
      ,type: 'line'
      ,yAxis: 2
    }]
  });
});
</script>
<div id="symbol_chart" style="width:1024px; height:500px;"></div>

<%= paginate @quotes %>
<p>
<table>
  <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Symbol</th>
    <th>Bid</th>
    <th>Offer</th>
    <th>Close</th>
    <th>Volume</th>
    <th>Buy:Sell</th>
  </tr>

<% @quotes.each do |quote| %>
  <tr>
    <td><%= quote.date %></td>
    <td><%= quote.time %></td>
    <td><%= quote.symbol %></td>
    <% if quote.symbol =~ /^SET/ or quote.symbol == 'mai' %>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    <% else %>
      <td><%= quote.bid %></td>
      <td><%= quote.offer %></td>
    <% end %>
    <td><%= quote.close %></td>
    <% if quote.symbol =~ /^SET/ or quote.symbol == 'mai' %>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    <% else %>
      <td><%= quote.vol_diff %></td>
      <td>
        <% if quote.vol_diff > 0 %>
          <%= raw quote.close == quote.offer ? "<font color='green'>BUY</font>" : "<font color='red'>SELL</font>" %>
        <% end %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', syms_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @quote.date %>
</p>

<p>
  <b>Time:</b>
  <%= @quote.time %>
</p>

<p>
  <b>Symbol:</b>
  <%= @quote.symbol %>
</p>

<p>
  <b>Close:</b>
  <%= @quote.close %>
</p>

<p>
  <b>Change:</b>
  <%= @quote.change %>
</p>

<p>
  <b>Perc change:</b>
  <%= @quote.perc_change %>
</p>

<p>
  <b>Volume:</b>
  <%= @quote.volume %>
</p>

<p>
  <b>Value:</b>
  <%= @quote.value %>
</p>


<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>