config/routes.rb
Stock::Application.routes.draw do
  resources :analyses

  get "chart/draw"

  resources :quotes

  resources :syms

  resources :setcloses

  match '/quotes/search(/:id)', :controller => :quotes, :action => :search
  match '/chart/draw/:id', :controller => :chart, :action => :draw
  match '/analyses/draw/:symbol/:date/:time', :controller => :analyses, :action => :draw
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/setcloses_controller.rb
class SetclosesController < ApplicationController
  # GET /setcloses
  # GET /setcloses.json
  def index
    @setcloses = Setclose.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @setcloses }
    end
  end

  # GET /setcloses/1
  # GET /setcloses/1.json
  def show
    @setclose = Setclose.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setclose }
    end
  end

  # GET /setcloses/new
  # GET /setcloses/new.json
  def new
    @setclose = Setclose.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setclose }
    end
  end

  # GET /setcloses/1/edit
  def edit
    @setclose = Setclose.find(params[:id])
  end

  # POST /setcloses
  # POST /setcloses.json
  def create
    @setclose = Setclose.new(params[:setclose])

    respond_to do |format|
      if @setclose.save
        format.html { redirect_to @setclose, notice: 'Setclose was successfully created.' }
        format.json { render json: @setclose, status: :created, location: @setclose }
      else
        format.html { render action: "new" }
        format.json { render json: @setclose.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /setcloses/1
  # PUT /setcloses/1.json
  def update
    @setclose = Setclose.find(params[:id])

    respond_to do |format|
      if @setclose.update_attributes(params[:setclose])
        format.html { redirect_to @setclose, notice: 'Setclose was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @setclose.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setcloses/1
  # DELETE /setcloses/1.json
  def destroy
    @setclose = Setclose.find(params[:id])
    @setclose.destroy

    respond_to do |format|
      format.html { redirect_to setcloses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/setcloses_helper.rb
module SetclosesHelper
end

app/views/setcloses/_form.html.erb
<%= form_for(@setclose) do |f| %>
  <% if @setclose.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setclose.errors.count, "error") %> prohibited this setclose from being saved:</h2>

      <ul>
      <% @setclose.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :close %><br />
    <%= f.text_field :close %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.number_field :volume %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setcloses/edit.html.erb
<h1>Editing setclose</h1>

<%= render 'form' %>

<%= link_to 'Show', @setclose %> |
<%= link_to 'Back', setcloses_path %>

app/views/setcloses/index.html.erb
<h1>Listing setcloses</h1>

<script type="text/javascript" charset="utf-8">
$(function(){
  new Highcharts.Chart({
    chart: {
      renderTo: "setcloses_chart"
    }
    ,title: {
      text: "SET Index"
    }
    ,xAxis: {
      categories: <%= raw @setcloses.map { |d| d['time'] } %>
      ,labels: {
        align: 'center'
        ,step: 1
	,rotation: 315
	,y: 20
      }
    }
    ,yAxis: [{
      title: {
        text: "Points"
      }
    },{
        opposite: true
        ,labels: {
          formatter: function() {
            return this.value / 1000000.0 + ' M Shares';
          }
          ,enabled: true
        }
        ,gridLineWidth: 0
        ,title: {
          text: 'Volume'
          ,style: { color: '#4500A7' }
        }
    }]
    ,series: [{
      name: 'Close'
      ,data: <%= @setcloses.map { |d| d.close } %>
      ,zIndex: 1
    },{
      name: 'Volume'
      ,data: <%= @setcloses.map { |d| d.vol_diff } %>
      ,type: 'column'
      ,yAxis: 1
    }]
  });
});
</script>
<div id="setcloses_chart" style="width:560px; height:300px;"></div>

<%= paginate @setcloses %>
<p>
<table>
  <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Close</th>
    <th>Volume</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @setcloses.each do |setclose| %>
  <tr>
    <td><%= setclose.date %></td>
    <td><%= setclose.time %></td>
    <td><%= setclose.close %></td>
    <td><%= setclose.volume %></td>
    <td><%= setclose.value %></td>
    <td><%= link_to 'Show', setclose %></td>
    <td><%= link_to 'Edit', edit_setclose_path(setclose) %></td>
    <td><%= link_to 'Destroy', setclose, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Setclose', new_setclose_path %>

app/views/setcloses/new.html.erb
<h1>New setclose</h1>

<%= render 'form' %>

<%= link_to 'Back', setcloses_path %>

app/views/setcloses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @setclose.date %>
</p>

<p>
  <b>Time:</b>
  <%= @setclose.time %>
</p>

<p>
  <b>Close:</b>
  <%= @setclose.close %>
</p>

<p>
  <b>Volume:</b>
  <%= @setclose.volume %>
</p>

<p>
  <b>Value:</b>
  <%= @setclose.value %>
</p>


<%= link_to 'Edit', edit_setclose_path(@setclose) %> |
<%= link_to 'Back', setcloses_path %>