config/routes.rb
Stock::Application.routes.draw do
  resources :analyses

  get "chart/draw"

  resources :quotes

  resources :syms

  resources :setcloses

  match '/quotes/search(/:id)', :controller => :quotes, :action => :search
  match '/chart/draw/:id', :controller => :chart, :action => :draw
  match '/analyses/draw/:symbol/:date/:time', :controller => :analyses, :action => :draw
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  # GET /analyses
  # GET /analyses.json
  def index
    @analyses = Analyse.all.order(['date',-1],['time',-1]).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @analyses }
    end
  end

  # GET /analyses/1
  # GET /analyses/1.json
  def show
    @analysis = Analyse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @analysis }
    end
  end

  # GET /analyses/new
  # GET /analyses/new.json
  def new
    @analysis = Analyse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @analysis }
    end
  end

  # GET /analyses/1/edit
  def edit
    @analysis = Analyse.find(params[:id])
  end

  # POST /analyses
  # POST /analyses.json
  def create
    @analysis = Analyse.new(params[:analysis])

    respond_to do |format|
      if @analysis.save
        format.html { redirect_to @analysis, notice: 'Analyse was successfully created.' }
        format.json { render json: @analysis, status: :created, location: @analysis }
      else
        format.html { render action: "new" }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /analyses/1
  # PUT /analyses/1.json
  def update
    @analysis = Analyse.find(params[:id])

    respond_to do |format|
      if @analysis.update_attributes(params[:analysis])
        format.html { redirect_to @analysis, notice: 'Analyse was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @analysis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analyses/1
  # DELETE /analyses/1.json
  def destroy
    @analysis = Analyse.find(params[:id])
    @analysis.destroy

    respond_to do |format|
      format.html { redirect_to analyses_url }
      format.json { head :ok }
    end
  end

  def draw
    @symbol = params[:symbol]
    @date = params[:date]
    @time = params[:time]
    @setcloses = Quote.where('date' => @date,'symbol' => 'SET').order(['time',1])
    @quotes = Quote.where('date' => @date,'symbol' => @symbol).order(['time',1])
  end

end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/views/analyses/_form.html.erb
<%= form_for(@analysis) do |f| %>
  <% if @analysis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@analysis.errors.count, "error") %> prohibited this analysis from being saved:</h2>

      <ul>
      <% @analysis.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br />
    <%= f.text_field :symbol %>
  </div>
  <div class="field">
    <%= f.label :perc_volume %><br />
    <%= f.text_field :perc_volume %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/analyses/draw.html.erb
<h1><%= link_to "Back to Analyses",  analyses_path %></h1>

<script type="text/javascript" charset="utf-8">
$(function(){
  new Highcharts.Chart({
    chart: {
      renderTo: "symbol_chart"
      ,zoomType: 'x'
    }
    ,title: {
      text: "<%= @symbol %>"
    }
    ,plotOptions: {
      areaspline: {
        fillColor: '#CCFFCC'
	,lineColor: '#CCFFCC'
	,color: '#CCFFCC'
      }
      ,series: {
	fillOpacity: .10
      }
    }
    ,xAxis: {
      categories: <%= raw @quotes.map { |d| d['time'] } %>
      ,labels: {
        align: 'center'
        ,step: 15
	,rotation: 315
	,y: 20
      }
    }
    ,yAxis: [{
      title: {
        text: "Price"
      }
    },{
        opposite: true
        ,labels: {
          formatter: function() {
            return this.value + ' Shares';
          }
          ,enabled: false
        }
        ,gridLineWidth: 0
        ,title: {
          text: 'Volume'
          ,style: { color: '#4500A7' }
        }
    },{
        opposite: false
        ,gridLineWidth: 0
        ,title: {
          text: 'SET'
          ,style: { color: '#450000' }
        }
    },{
        opposite: true
        ,gridLineWidth: 0
        ,title: {
          text: '%Volume'
          ,style: { color: '#454500' }
        }
    }]
    ,tooltip: {
      crosshairs: true
      ,shared: true
    }
    ,series: [{
      name: 'Close'
      ,data: <%= @quotes.map { |d| d.close } %>
      ,zIndex: 4
    },{
      name: 'Volume'
      ,data: <%= @quotes.map { |d| d.vol_diff } %>
      ,type: 'column'
      ,yAxis: 1
      ,zIndex: 3
    },{
      name: 'SET'
      ,data: <%= @setcloses.map { |d| d.close } %>
      ,type: 'line'
      ,yAxis: 2
      ,zIndex: 2
    },{
      name: '%Volume'
      ,data: <%= raw @quotes.map { |d| d.perc_volume.to_f } %>
      ,type: 'areaspline'
      ,yAxis: 3
      ,zIndex: -1
    }]
  });
});
</script>
<div id="symbol_chart" style="width:1024px; height:500px;"></div>

app/views/analyses/edit.html.erb
<h1>Editing analysis</h1>

<%= render 'form' %>

<%= link_to 'Show', @analysis %> |
<%= link_to 'Back', analyses_path %>

app/views/analyses/index.html.erb
<h1>Listing analyses</h1>

<%= paginate @analyses %>
<p>
<table>
  <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Symbol</th>
    <th>Perc volume</th>
    <th>Close</th>
    <th>Change</th>
 </tr>

<% @analyses.each do |analysis| %>
  <tr>
    <td><%= analysis.date %></td>
    <td><%= analysis.time %></td>
    <td><%= link_to analysis.symbol, "/analyses/draw/#{analysis.symbol}/#{analysis.date}/#{analysis.time}" %></td>
    <td><%= analysis.perc_volume %></td>
    <td><%= analysis.close %></td>
    <td><%= analysis.change %></td>
  </tr>
<% end %>
</table>

<br />

<%# link_to 'New Analyse', new_analysis_path %>

app/views/analyses/new.html.erb
<h1>New analysis</h1>

<%= render 'form' %>

<%= link_to 'Back', analyses_path %>

app/views/analyses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @analysis.date %>
</p>

<p>
  <b>Time:</b>
  <%= @analysis.time %>
</p>

<p>
  <b>Symbol:</b>
  <%= @analysis.symbol %>
</p>

<p>
  <b>Perc volume:</b>
  <%= @analysis.perc_volume %>
</p>


<%= link_to 'Edit', edit_analysis_path(@analysis) %> |
<%= link_to 'Back', analyses_path %>