config/routes.rb
Stock::Application.routes.draw do
  resources :analyses

  get "chart/draw"

  resources :quotes

  resources :syms

  resources :setcloses

  match '/quotes/search(/:id)', :controller => :quotes, :action => :search
  match '/chart/draw/:id', :controller => :chart, :action => :draw
  match '/analyses/draw/:symbol/:date/:time', :controller => :analyses, :action => :draw
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/sym.rb
class Sym
  include Mongoid::Document
  field :name, :type => String
end

app/controllers/syms_controller.rb
class SymsController < ApplicationController
  # GET /syms
  # GET /syms.json
  def index
    @syms = Sym.page(params[:page]).per(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @syms }
    end
  end

  # GET /syms/1
  # GET /syms/1.json
  def show
    @sym = Sym.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sym }
    end
  end

  # GET /syms/new
  # GET /syms/new.json
  def new
    @sym = Sym.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sym }
    end
  end

  # GET /syms/1/edit
  def edit
    @sym = Sym.find(params[:id])
  end

  # POST /syms
  # POST /syms.json
  def create
    @sym = Sym.new(params[:sym])

    respond_to do |format|
      if @sym.save
        format.html { redirect_to @sym, notice: 'Sym was successfully created.' }
        format.json { render json: @sym, status: :created, location: @sym }
      else
        format.html { render action: "new" }
        format.json { render json: @sym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /syms/1
  # PUT /syms/1.json
  def update
    @sym = Sym.find(params[:id])

    respond_to do |format|
      if @sym.update_attributes(params[:sym])
        format.html { redirect_to @sym, notice: 'Sym was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @sym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syms/1
  # DELETE /syms/1.json
  def destroy
    @sym = Sym.find(params[:id])
    @sym.destroy

    respond_to do |format|
      format.html { redirect_to syms_url }
      format.json { head :ok }
    end
  end
end

app/helpers/syms_helper.rb
module SymsHelper
end

app/views/syms/_form.html.erb
<%= form_for(@sym) do |f| %>
  <% if @sym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sym.errors.count, "error") %> prohibited this sym from being saved:</h2>

      <ul>
      <% @sym.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/syms/edit.html.erb
<h1>Editing sym</h1>

<%= render 'form' %>

<%= link_to 'Show', @sym %> |
<%= link_to 'Back', syms_path %>

app/views/syms/index.html.erb
<h1>Listing syms</h1>

<%= paginate @syms %>
<p>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @syms.each do |sym| %>
  <tr>
    <td><%= link_to sym.name, "/quotes/search/#{sym.name}" %></td>
    <td><%= link_to 'Show', sym %></td>
    <td><%= link_to 'Edit', edit_sym_path(sym) %></td>
    <td><%= link_to 'Destroy', sym, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%# link_to 'New Sym', new_sym_path %>

app/views/syms/new.html.erb
<h1>New sym</h1>

<%= render 'form' %>

<%= link_to 'Back', syms_path %>

app/views/syms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sym.name %>
</p>


<%= link_to 'Edit', edit_sym_path(@sym) %> |
<%= link_to 'Back', syms_path %>